### ISSUE TITLE
allow to specify multiple dtypes in spec yamls

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/python-bioimage-io#26]
```yaml
inputs:
 - ...
   data_type: [float32, uint8]
```
